### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by zzohouri** [aliayub7/CBCL#2]
Dear AliAyub,
Thank you for sharing your code.
Can you please explain how is your code supposed to work when you are appending all the data into a list? How is it possible not to overload the RAM with your code? What is going on here?

**Comment by aliayub7** [comment]
Dear zzohouri,
I am not sure what you mean by how it is supposed to work? The dataset is small enough at each increment so that we can use a list to store all of it. If you are not able to reproduce the results of the paper, let us know. However, I have rechecked the code and it is running fine.

**Comment by zzohouri** [comment]
Dear Aliayub,
The dataset it self is not the issue, first you extract the features using resnet18, then you call the getIncrementalData class, and in this class, in lines 74 and 78 you have: 
self.train_features_increment[increment].append(train_features[j])

This causes the RAM to be overflowed and causes a crash on Google Colab, even with 25GB of RAM!!!!!
Please explain what am I doing wrong?

**Comment by zzohouri** [comment]
> Dear Aliayub, The dataset it self is not the issue, first you extract the features using resnet18, then you call the getIncrementalData class, and in this class, in lines 74 and 78 you have: self.train_features_increment[increment].append(train_features[j])
> 
> This causes the RAM to be overflowed and causes a crash on Google Colab, even with 25GB of RAM!!!!! Please explain what am I doing wrong?

This is by the way for caltech101 dataset

**Comment by zzohouri** [comment]
I am using Resnet18 pretrained on imagenet, and I get the output of layer(4) of resnet and then perform a mean(3).mean(2).squeeze() o the extracted features, although I lowered the input size to 12x12 instead of 224x224 or etc, still I get the RAM memory issue. Please help.

**Comment by aliayub7** [comment]
For a 224x224 input, the feature vectors are of size 512x1. Please confirm that each feature vector is of this size. Also, please check the sizes for train_features in the get_incremental_data.py file. 

Line 74 to 78 are simply putting the input data into smaller chunks to be used in multiple increments. So, the size of this new array should not be greater than the train_features array.

**Comment by zzohouri** [comment]
Dear Ali, thank you very much for your collaboration and your replies. I really appreciate it. 

I am going to check on the data sizes as you mentioned above. I let you know how it goes, again thanks for the help.

**Comment by zzohouri** [comment]
also this line is not working: from classification_models.keras import Classifiers
even when i do pip install classification_models
can you please help?

**Comment by zzohouri** [comment]
I figured the last one out, It's because the package was written in python 2.7 now we are using python 3.

**Comment by zzohouri** [comment]
Dear Ali, would you please tell me how to produce 512x1 feature vectors from Resnet18? Thanks

**Comment by zzohouri** [comment]
I got it, its the output of last pooling layer before the fc layer. Thanks again.

**Comment by zzohouri** [comment]
Thank you for sharing your code and thank you for your help here agin.
